[params.plausible]
  domain = "yannickschutz.com"
[build]
  writeStats = true
[params.stripe]
  key = "pk_live_51IkUQkFaA8Wpl3EpMpvlAmMmPpUd01DC9lQhm4EmjE2riwTzkQn5frrtnlet2bL5sqXdzP1eTnpp7fbwUytfvUDd0093FkdcTD"
  shipping = "shr_1IkYnWFaA8Wpl3Ep1BqvXP4y"
